### ISSUE TITLE
Errors when building the .so files

### ISSUE THREAD

**Issue by deephog** [MAhaitao999/TensorRT_Plugin_Template#1]
Thank you for you nice work. I would like to try your gridsampler plug for my model, and the TRT version I am using is 8.4. When building the .so files, I encountered the following errors. Looks like it is because of the version compatibility, lots of the functions you override have different protocols. Do you have any suggestion of how to make the plugin 8.4 compatible? Thanks! 

../plugins/GridSamplerPlugin.h(87): error: exception specification for virtual function "GridSamplerPlugin::detachFromContext" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::detachFromContext"

../plugins/GridSamplerPlugin.h(86): error: exception specification for virtual function "GridSamplerPlugin::attachToContext" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::attachToContext"

../plugins/GridSamplerPlugin.h(85): error: exception specification for virtual function "GridSamplerPlugin::getPluginVersion" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginVersion"

../plugins/GridSamplerPlugin.h(84): error: exception specification for virtual function "GridSamplerPlugin::getPluginType" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginType"

../plugins/GridSamplerPlugin.h(83): error: exception specification for virtual function "GridSamplerPlugin::getPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginNamespace"

../plugins/GridSamplerPlugin.h(82): error: exception specification for virtual function "GridSamplerPlugin::setPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginV2::setPluginNamespace"

../plugins/GridSamplerPlugin.h(81): error: exception specification for virtual function "GridSamplerPlugin::destroy" is incompatible with that of overridden function "nvinfer1::IPluginV2::destroy"

../plugins/GridSamplerPlugin.h(80): error: exception specification for virtual function "GridSamplerPlugin::terminate" is incompatible with that of overridden function "nvinfer1::IPluginV2::terminate"

../plugins/GridSamplerPlugin.h(79): error: exception specification for virtual function "GridSamplerPlugin::initialize" is incompatible with that of overridden function "nvinfer1::IPluginV2::initialize"

../plugins/GridSamplerPlugin.h(77): error: exception specification for virtual function "GridSamplerPlugin::enqueue(const nvinfer1::PluginTensorDesc *, const nvinfer1::PluginTensorDesc *, const void *const *, void *const *, void *, cudaStream_t)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::enqueue(const nvinfer1::PluginTensorDesc *, const nvinfer1::PluginTensorDesc *, const void *const *, void *const *, void *, cudaStream_t) noexcept"

../plugins/GridSamplerPlugin.h(76): error: exception specification for virtual function "GridSamplerPlugin::getWorkspaceSize(const nvinfer1::PluginTensorDesc *, int32_t, const nvinfer1::PluginTensorDesc *, int32_t) const" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::getWorkspaceSize(const nvinfer1::PluginTensorDesc *, int32_t, const nvinfer1::PluginTensorDesc *, int32_t) const noexcept"

../plugins/GridSamplerPlugin.h(72): error: exception specification for virtual function "GridSamplerPlugin::configurePlugin(const nvinfer1::DynamicPluginTensorDesc *, int, const nvinfer1::DynamicPluginTensorDesc *, int)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::configurePlugin(const nvinfer1::DynamicPluginTensorDesc *, int32_t, const nvinfer1::DynamicPluginTensorDesc *, int32_t) noexcept"

../plugins/GridSamplerPlugin.h(68): error: exception specification for virtual function "GridSamplerPlugin::getOutputDataType" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::getOutputDataType"

../plugins/GridSamplerPlugin.h(62): error: exception specification for virtual function "GridSamplerPlugin::getOutputDimensions(int, const nvinfer1::DimsExprs *, int, nvinfer1::IExprBuilder &)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::getOutputDimensions(int32_t, const nvinfer1::DimsExprs *, int32_t, nvinfer1::IExprBuilder &) noexcept"

../plugins/GridSamplerPlugin.h(59): error: exception specification for virtual function "GridSamplerPlugin::getNbOutputs" is incompatible with that of overridden function "nvinfer1::IPluginV2::getNbOutputs"

../plugins/GridSamplerPlugin.h(45): error: exception specification for virtual function "GridSamplerPlugin::supportsFormatCombination" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::supportsFormatCombination"

../plugins/GridSamplerPlugin.h(41): error: exception specification for virtual function "GridSamplerPlugin::clone" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::clone"

../plugins/GridSamplerPlugin.h(39): error: exception specification for virtual function "GridSamplerPlugin::serialize" is incompatible with that of overridden function "nvinfer1::IPluginV2::serialize"

../plugins/GridSamplerPlugin.h(36): error: exception specification for virtual function "GridSamplerPlugin::getSerializationSize" is incompatible with that of overridden function "nvinfer1::IPluginV2::getSerializationSize"

../plugins/GridSamplerPlugin.h(121): error: exception specification for virtual function "GridSamplerPluginCreator::createPlugin" is incompatible with that of overridden function "nvinfer1::IPluginCreator::createPlugin"

../plugins/GridSamplerPlugin.h(117): error: exception specification for virtual function "GridSamplerPluginCreator::getFieldNames" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getFieldNames"

../plugins/GridSamplerPlugin.h(115): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginNamespace"

../plugins/GridSamplerPlugin.h(114): error: exception specification for virtual function "GridSamplerPluginCreator::setPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginCreator::setPluginNamespace"

../plugins/GridSamplerPlugin.h(112): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginVersion" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginVersion"

../plugins/GridSamplerPlugin.h(111): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginName" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginName"

../plugins/GridSamplerPlugin.h(107): error: exception specification for virtual function "GridSamplerPluginCreator::deserializePlugin" is incompatible with that of overridden function "nvinfer1::IPluginCreator::deserializePlugin"

**Comment by MAhaitao999** [comment]
> Thank you for you nice work. I would like to try your gridsampler plug for my model, and the TRT version I am using is 8.4. When building the .so files, I encountered the following errors. Looks like it is because of the version compatibility, lots of the functions you override have different protocols. Do you have any suggestion of how to make the plugin 8.4 compatible? Thanks!
> 
> ../plugins/GridSamplerPlugin.h(87): error: exception specification for virtual function "GridSamplerPlugin::detachFromContext" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::detachFromContext"
> 
> ../plugins/GridSamplerPlugin.h(86): error: exception specification for virtual function "GridSamplerPlugin::attachToContext" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::attachToContext"
> 
> ../plugins/GridSamplerPlugin.h(85): error: exception specification for virtual function "GridSamplerPlugin::getPluginVersion" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginVersion"
> 
> ../plugins/GridSamplerPlugin.h(84): error: exception specification for virtual function "GridSamplerPlugin::getPluginType" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginType"
> 
> ../plugins/GridSamplerPlugin.h(83): error: exception specification for virtual function "GridSamplerPlugin::getPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginNamespace"
> 
> ../plugins/GridSamplerPlugin.h(82): error: exception specification for virtual function "GridSamplerPlugin::setPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginV2::setPluginNamespace"
> 
> ../plugins/GridSamplerPlugin.h(81): error: exception specification for virtual function "GridSamplerPlugin::destroy" is incompatible with that of overridden function "nvinfer1::IPluginV2::destroy"
> 
> ../plugins/GridSamplerPlugin.h(80): error: exception specification for virtual function "GridSamplerPlugin::terminate" is incompatible with that of overridden function "nvinfer1::IPluginV2::terminate"
> 
> ../plugins/GridSamplerPlugin.h(79): error: exception specification for virtual function "GridSamplerPlugin::initialize" is incompatible with that of overridden function "nvinfer1::IPluginV2::initialize"
> 
> ../plugins/GridSamplerPlugin.h(77): error: exception specification for virtual function "GridSamplerPlugin::enqueue(const nvinfer1::PluginTensorDesc *, const nvinfer1::PluginTensorDesc *, const void *const *, void *const *, void *, cudaStream_t)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::enqueue(const nvinfer1::PluginTensorDesc *, const nvinfer1::PluginTensorDesc *, const void *const *, void *const *, void *, cudaStream_t) noexcept"
> 
> ../plugins/GridSamplerPlugin.h(76): error: exception specification for virtual function "GridSamplerPlugin::getWorkspaceSize(const nvinfer1::PluginTensorDesc *, int32_t, const nvinfer1::PluginTensorDesc *, int32_t) const" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::getWorkspaceSize(const nvinfer1::PluginTensorDesc *, int32_t, const nvinfer1::PluginTensorDesc *, int32_t) const noexcept"
> 
> ../plugins/GridSamplerPlugin.h(72): error: exception specification for virtual function "GridSamplerPlugin::configurePlugin(const nvinfer1::DynamicPluginTensorDesc *, int, const nvinfer1::DynamicPluginTensorDesc *, int)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::configurePlugin(const nvinfer1::DynamicPluginTensorDesc *, int32_t, const nvinfer1::DynamicPluginTensorDesc *, int32_t) noexcept"
> 
> ../plugins/GridSamplerPlugin.h(68): error: exception specification for virtual function "GridSamplerPlugin::getOutputDataType" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::getOutputDataType"
> 
> ../plugins/GridSamplerPlugin.h(62): error: exception specification for virtual function "GridSamplerPlugin::getOutputDimensions(int, const nvinfer1::DimsExprs *, int, nvinfer1::IExprBuilder &)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::getOutputDimensions(int32_t, const nvinfer1::DimsExprs *, int32_t, nvinfer1::IExprBuilder &) noexcept"
> 
> ../plugins/GridSamplerPlugin.h(59): error: exception specification for virtual function "GridSamplerPlugin::getNbOutputs" is incompatible with that of overridden function "nvinfer1::IPluginV2::getNbOutputs"
> 
> ../plugins/GridSamplerPlugin.h(45): error: exception specification for virtual function "GridSamplerPlugin::supportsFormatCombination" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::supportsFormatCombination"
> 
> ../plugins/GridSamplerPlugin.h(41): error: exception specification for virtual function "GridSamplerPlugin::clone" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::clone"
> 
> ../plugins/GridSamplerPlugin.h(39): error: exception specification for virtual function "GridSamplerPlugin::serialize" is incompatible with that of overridden function "nvinfer1::IPluginV2::serialize"
> 
> ../plugins/GridSamplerPlugin.h(36): error: exception specification for virtual function "GridSamplerPlugin::getSerializationSize" is incompatible with that of overridden function "nvinfer1::IPluginV2::getSerializationSize"
> 
> ../plugins/GridSamplerPlugin.h(121): error: exception specification for virtual function "GridSamplerPluginCreator::createPlugin" is incompatible with that of overridden function "nvinfer1::IPluginCreator::createPlugin"
> 
> ../plugins/GridSamplerPlugin.h(117): error: exception specification for virtual function "GridSamplerPluginCreator::getFieldNames" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getFieldNames"
> 
> ../plugins/GridSamplerPlugin.h(115): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginNamespace"
> 
> ../plugins/GridSamplerPlugin.h(114): error: exception specification for virtual function "GridSamplerPluginCreator::setPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginCreator::setPluginNamespace"
> 
> ../plugins/GridSamplerPlugin.h(112): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginVersion" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginVersion"
> 
> ../plugins/GridSamplerPlugin.h(111): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginName" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginName"
> 
> ../plugins/GridSamplerPlugin.h(107): error: exception specification for virtual function "GridSamplerPluginCreator::deserializePlugin" is incompatible with that of overridden function "nvinfer1::IPluginCreator::deserializePlugin"

My version is v7. sorry I have no experience in using v8.4.

**Comment by deephog** [comment]
> > Thank you for you nice work. I would like to try your gridsampler plug for my model, and the TRT version I am using is 8.4. When building the .so files, I encountered the following errors. Looks like it is because of the version compatibility, lots of the functions you override have different protocols. Do you have any suggestion of how to make the plugin 8.4 compatible? Thanks!
> > ../plugins/GridSamplerPlugin.h(87): error: exception specification for virtual function "GridSamplerPlugin::detachFromContext" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::detachFromContext"
> > ../plugins/GridSamplerPlugin.h(86): error: exception specification for virtual function "GridSamplerPlugin::attachToContext" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::attachToContext"
> > ../plugins/GridSamplerPlugin.h(85): error: exception specification for virtual function "GridSamplerPlugin::getPluginVersion" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginVersion"
> > ../plugins/GridSamplerPlugin.h(84): error: exception specification for virtual function "GridSamplerPlugin::getPluginType" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginType"
> > ../plugins/GridSamplerPlugin.h(83): error: exception specification for virtual function "GridSamplerPlugin::getPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginV2::getPluginNamespace"
> > ../plugins/GridSamplerPlugin.h(82): error: exception specification for virtual function "GridSamplerPlugin::setPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginV2::setPluginNamespace"
> > ../plugins/GridSamplerPlugin.h(81): error: exception specification for virtual function "GridSamplerPlugin::destroy" is incompatible with that of overridden function "nvinfer1::IPluginV2::destroy"
> > ../plugins/GridSamplerPlugin.h(80): error: exception specification for virtual function "GridSamplerPlugin::terminate" is incompatible with that of overridden function "nvinfer1::IPluginV2::terminate"
> > ../plugins/GridSamplerPlugin.h(79): error: exception specification for virtual function "GridSamplerPlugin::initialize" is incompatible with that of overridden function "nvinfer1::IPluginV2::initialize"
> > ../plugins/GridSamplerPlugin.h(77): error: exception specification for virtual function "GridSamplerPlugin::enqueue(const nvinfer1::PluginTensorDesc *, const nvinfer1::PluginTensorDesc *, const void *const *, void *const *, void *, cudaStream_t)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::enqueue(const nvinfer1::PluginTensorDesc *, const nvinfer1::PluginTensorDesc *, const void *const *, void *const *, void *, cudaStream_t) noexcept"
> > ../plugins/GridSamplerPlugin.h(76): error: exception specification for virtual function "GridSamplerPlugin::getWorkspaceSize(const nvinfer1::PluginTensorDesc *, int32_t, const nvinfer1::PluginTensorDesc *, int32_t) const" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::getWorkspaceSize(const nvinfer1::PluginTensorDesc *, int32_t, const nvinfer1::PluginTensorDesc *, int32_t) const noexcept"
> > ../plugins/GridSamplerPlugin.h(72): error: exception specification for virtual function "GridSamplerPlugin::configurePlugin(const nvinfer1::DynamicPluginTensorDesc *, int, const nvinfer1::DynamicPluginTensorDesc *, int)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::configurePlugin(const nvinfer1::DynamicPluginTensorDesc *, int32_t, const nvinfer1::DynamicPluginTensorDesc *, int32_t) noexcept"
> > ../plugins/GridSamplerPlugin.h(68): error: exception specification for virtual function "GridSamplerPlugin::getOutputDataType" is incompatible with that of overridden function "nvinfer1::IPluginV2Ext::getOutputDataType"
> > ../plugins/GridSamplerPlugin.h(62): error: exception specification for virtual function "GridSamplerPlugin::getOutputDimensions(int, const nvinfer1::DimsExprs *, int, nvinfer1::IExprBuilder &)" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::getOutputDimensions(int32_t, const nvinfer1::DimsExprs *, int32_t, nvinfer1::IExprBuilder &) noexcept"
> > ../plugins/GridSamplerPlugin.h(59): error: exception specification for virtual function "GridSamplerPlugin::getNbOutputs" is incompatible with that of overridden function "nvinfer1::IPluginV2::getNbOutputs"
> > ../plugins/GridSamplerPlugin.h(45): error: exception specification for virtual function "GridSamplerPlugin::supportsFormatCombination" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::supportsFormatCombination"
> > ../plugins/GridSamplerPlugin.h(41): error: exception specification for virtual function "GridSamplerPlugin::clone" is incompatible with that of overridden function "nvinfer1::IPluginV2DynamicExt::clone"
> > ../plugins/GridSamplerPlugin.h(39): error: exception specification for virtual function "GridSamplerPlugin::serialize" is incompatible with that of overridden function "nvinfer1::IPluginV2::serialize"
> > ../plugins/GridSamplerPlugin.h(36): error: exception specification for virtual function "GridSamplerPlugin::getSerializationSize" is incompatible with that of overridden function "nvinfer1::IPluginV2::getSerializationSize"
> > ../plugins/GridSamplerPlugin.h(121): error: exception specification for virtual function "GridSamplerPluginCreator::createPlugin" is incompatible with that of overridden function "nvinfer1::IPluginCreator::createPlugin"
> > ../plugins/GridSamplerPlugin.h(117): error: exception specification for virtual function "GridSamplerPluginCreator::getFieldNames" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getFieldNames"
> > ../plugins/GridSamplerPlugin.h(115): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginNamespace"
> > ../plugins/GridSamplerPlugin.h(114): error: exception specification for virtual function "GridSamplerPluginCreator::setPluginNamespace" is incompatible with that of overridden function "nvinfer1::IPluginCreator::setPluginNamespace"
> > ../plugins/GridSamplerPlugin.h(112): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginVersion" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginVersion"
> > ../plugins/GridSamplerPlugin.h(111): error: exception specification for virtual function "GridSamplerPluginCreator::getPluginName" is incompatible with that of overridden function "nvinfer1::IPluginCreator::getPluginName"
> > ../plugins/GridSamplerPlugin.h(107): error: exception specification for virtual function "GridSamplerPluginCreator::deserializePlugin" is incompatible with that of overridden function "nvinfer1::IPluginCreator::deserializePlugin"
> 
> My version is v7. sorry I have no experience in using v8.4.

Thank you for your reply!
